name: Dump
description: |
環境変数とgitHubコンテキストをログへ出力

inputs:
  enable-context:
    description: 'コンテキストを出力するかどうか'
    required: false
    default: 'true'

outputs:
  dumped-date:
    value: ${{steps.current.outputs.date}}
    description: 'ダンプした日時'

runs:
  using: composite
  steps:
    - run: printenv | sort
      shell: bash
    - run: echo "${CONTEXT}"
      if: ${{ inputs.enable-context == 'true' }}
      env:
        CONTEXT: ${{ toJSON(github) }}
      shell: bash
    - id: current
      run: echo "date=$(date)" >> "${GITHUB_OUTPUT}"
      shell: bash
      