name: Parallel
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 &&echo "First job"
    second-job:
        runs-on: ubuntu-latest
        needs: first-job
        steps:
            - run: sleep 10 && echo "Second job"
    third-job:
        runs-on: ubuntu-latest
        needs: [first-job, second-job]
        steps:
            - run: sleep 10 && echo "Third job"
